DROP TABLE IF EXISTS USER;
DROP TABLE IF EXISTS STOCK;
DROP TABLE IF EXISTS BOUGHTSTOCKS;

CREATE TABLE USER (
	ID INT NOT NULL AUTO_INCREMENT, 
	BALANCE INT,
	PRIMARY KEY (ID));
	
CREATE TABLE STOCK ( 
	ID INT NOT NULL AUTO_INCREMENT, 
	COMPANY VARCHAR(200), 
	PRICE INT, 
	PRICECHANGE INT,
	PRIMARY KEY (ID));
	
CREATE TABLE BOUGHTSTOCKS ( 
	ID INT NOT NULL AUTO_INCREMENT,
	USERID INT, 
	STOCKID INT, 
	FOREIGN KEY (USERID) REFERENCES USER(ID), 
	FOREIGN KEY (STOCKID) REFERENCES STOCK(ID) );